version: '3.8'

services:
  backend:
    image: ghcr.io/nextestudios/nextclinic-backend:latest
    container_name: nextclinic_backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=super-secret-jwt-key
      - JWT_EXPIRATION=1d
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user123
      - DATABASE_NAME=vacinacao_db
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "3001:3000"

  nextclinic:
    image: ghcr.io/nextestudios/nextclinic:latest
    container_name: nextclinic
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://62.171.139.44:3001
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: vacinacao_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacinacao_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: vacinacao_adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
